### ISSUE TITLE
존재하지 않는 userId 예외처리 필요

### ISSUE THREAD

**Issue by bengHak** [DSCHUFS/bucketlist-sns#39]
https://github.com/DSCHUFS/bucketlist-sns/blob/cea80fdb7e10b80c25e6732c7e90586e49e7c97b/backend/controller/user.js#L8

**Comment by ujin2021** [comment]
res.status(400).json({'msg':`Invalid user id`})
status code 400, 'Invalid user id'로 처리했어요
